### PR TITLE
fix: Eliminate circular import on helpers

### PR DESCRIPTION
**Pull request by raulgomezc**
Closes [Ticket](https://trello.com)

## Testing

Steps to manually verify the change:
1. _Setup_: step to set the environment
2. _Exercise_: How to run the environment and example link: [Test Link](http://127.0.0.1:8000/)
3. _Verify_: what we need to verify

### CODE REVIEW

**Comment by oscarpolanco** [comment]
Hey nice job!!! 👍 
One thing; can we change the name of the `Extended_Node` to another name that match the implemantation

**Review by mariamera — APPROVED** [review]
Good 👍

**Review by junior1q94 — APPROVED** [review]
LGTM

**Comment by junior1q94** [comment]
@oscarpolanco @raulgomezc @mariamera ^

**Pull request merged**
